import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Footer from "../_components/Footer";
import Navbar from "../_components/Navbar";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Daily Muse",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className}  antialiased`}>
        {/* <StoreProvider> */}
        {/* <ReactQueryProviders> */}
        <Navbar />
        {children}
        <Footer />
        {/* </ReactQueryProviders> */}
        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
