import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "@/providers/ReactQueryProvider";
import StoreProvider from "@/providers/StoreProvider";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Daily Muse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className}  antialiased`}>
        {/* <StoreProvider> */}
        <ReactQueryProviders>
          <Navbar />
          {children}
          <Footer />
        </ReactQueryProviders>
        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
